In [ ]:
from pyspark.sql import SparkSession

In [ ]:
#Starting a Spark Session
spark = SparkSession.builder.appName('Basics').getOrCreate()

In [ ]:
#Importing the JSON file to a dataframe
df = spark.read.json('/FileStore/tables/people.json')

In [ ]:
df.show()

+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|  30|   Andy|
|  19| Justin|
+----+-------+

In [ ]:
df.printSchema()

root
 |-- age: long (nullable = true)
 |-- name: string (nullable = true)

In [ ]:
df.columns

Out[13]: ['age', 'name']

In [ ]:
df.describe().show()

+-------+------------------+-------+
|summary|               age|   name|
+-------+------------------+-------+
|  count|                 2|      3|
|   mean|              24.5|   null|
| stddev|7.7781745930520225|   null|
|    min|                19|   Andy|
|    max|                30|Michael|
+-------+------------------+-------+

In [ ]:
#Changing the schema
from pyspark.sql.types import StructField,StringType,IntegerType,StructType

In [ ]:
#Creating a schema
data_schema = [StructField('age',IntegerType(),True),
              StructField('name',StringType(),True)]

In [ ]:
#Creating a variable of StructType with fields set to the created schema
final_struc = StructType(fields=data_schema)

In [ ]:
#Reading the JSON file by specifying our schema
df = spark.read.json('/FileStore/tables/people.json',schema=final_struc)

In [ ]:
df.printSchema()

root
 |-- age: integer (nullable = true)
 |-- name: string (nullable = true)

In [ ]:
df.show()

+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|  30|   Andy|
|  19| Justin|
+----+-------+

In [ ]:
#Grabbing data
#Selecting only the required column
#This just returns a column
df['age']

Out[24]: Column<'age'>

In [ ]:
#Selecting only the required column
#This returns a df of the column
df.select('age').show()

+----+
| age|
+----+
|null|
|  30|
|  19|
+----+

In [ ]:
#Selecting Multiple columns
df.select(['age','name']).show()

+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|  30|   Andy|
|  19| Justin|
+----+-------+

In [ ]:
#Getting row entries
#This returns a list of row objects
df.head(2)

Out[25]: [Row(age=None, name='Michael'), Row(age=30, name='Andy')]

In [ ]:
#Creating new columns
df.withColumn('double_age',df['age']*2).show()
#will have to do inplace to save to original df

+----+-------+----------+
| age|   name|double_age|
+----+-------+----------+
|null|Michael|      null|
|  30|   Andy|        60|
|  19| Justin|        38|
+----+-------+----------+

In [ ]:
#Renaming a column
df.withColumnRenamed(existing='age',new='new_age').show()

+-------+-------+
|new_age|   name|
+-------+-------+
|   null|Michael|
|     30|   Andy|
|     19| Justin|
+-------+-------+

In [ ]:
#Using SQL to get data
df.createOrReplaceTempView('people')

In [ ]:
results = spark.sql("SELECT * FROM people")

In [ ]:
results.show()

+----+-------+
| age|   name|
+----+-------+
|null|Michael|
|  30|   Andy|
|  19| Justin|
+----+-------+

In [ ]:
new_results = spark.sql("SELECT * FROM people WHERE age=19")
new_results.show()

+---+------+
|age|  name|
+---+------+
| 19|Justin|
+---+------+